import { SimulationPolicy, StageDefinition } from './models';

export const DEFAULT_POLICY: SimulationPolicy = {
  runDate: '2026-06-01',
  historyYears: 3,
  cycleLength: 15,
  cutoffHour: '10:00',
  referenceRadius: 7,
  maxReferenceRadius: 24,
  minimumReferences: 3,
  maxBalancedPerSide: 7,
  version: 'DP-2026.06-v1',
  periodBudget: 4_000_000_000,
};

export const STAGES: readonly StageDefinition[] = [
  { number: 1, phase: 1, title: 'Khoảng lịch sử & chia chu kỳ', shortTitle: 'Khung lịch', goal: 'Khóa phạm vi dữ liệu và nhịp chu kỳ lịch cố định.', flow: ['Đọc tham số phiên', 'Xác định năm', 'Khóa ngày đầu/cuối', 'Tạo lịch ngày', 'Chia chu kỳ', 'Tính ngày dư', 'Gắn dữ liệu vào lịch'], formula: 'N = ⌊D / M⌋; r = D − N×M', variables: [{ symbol: 'D', meaning: 'Tổng số ngày lịch trong phạm vi' }, { symbol: 'M', meaning: 'Độ dài một chu kỳ kế hoạch, mặc định 15 ngày' }, { symbol: 'N', meaning: 'Số chu kỳ đầy đủ được phép học' }, { symbol: 'r', meaning: 'Số ngày dư ở biên, chỉ giữ để kiểm toán' }] },
  { number: 2, phase: 1, title: 'Đánh dấu stockout', shortTitle: 'Stockout', goal: 'Chỉ nhận diện ngày thiếu hàng theo đúng hai điều kiện.', flow: ['Tồn đầu/cuối', 'Giờ nhập đầu tiên', 'Kiểm tra 2 điều kiện', 'Gắn cờ'], formula: '(O=0 ∧ C>0 ∧ h>h₀) ∨ (O=0 ∧ C=0 ∧ Q=0)', variables: [{ symbol: 'O/C', meaning: 'Tồn đầu ngày / cuối ngày' }, { symbol: 'h', meaning: 'Giờ nhập đầu tiên trong ngày' }, { symbol: 'h₀', meaning: 'Giờ quy định nhập hàng' }, { symbol: 'Q', meaning: 'Số bán ghi nhận' }] },
  { number: 3, phase: 1, title: 'Nâng nền ngày stockout', shortTitle: 'Nền stockout', goal: 'Ước lượng sức mua tự nhiên từ ngày sạch quan sát.', flow: ['Phân luồng CTKM', 'Kiểm tra stockout', 'Tìm sạch ±7', 'Cân bằng hai phía', 'Mở rộng ≤24', 'Median', 'max(Q,R)', 'Bàn giao'], formula: 'k = min(n₋, n₊, 7); Bₜ = max(Qₜ, Median(Rₜ))', variables: [{ symbol: 't', meaning: 'Ngày đang được xử lý trong chuỗi thời gian' }, { symbol: 'n₋/n₊', meaning: 'Số ngày sạch tìm được trước / sau ngày t' }, { symbol: 'k', meaning: 'Số ngày gần nhất lấy ở mỗi phía; không phải hệ số tùy ý' }, { symbol: 'Rₜ', meaning: 'Tập ngày sạch tham chiếu của ngày t' }, { symbol: 'Bₜ', meaning: 'Sức mua cơ bản của ngày t' }] },
  { number: 4, phase: 1, title: 'Đưa CTKM về mức bán tự nhiên', shortTitle: 'Chuẩn hóa KM', goal: 'Loại hiệu ứng tăng bán của CTKM khỏi dữ liệu nền.', flow: ['Dựng vùng/cụm CTKM', 'Chặn CTKM liền kề', 'Tìm sạch ±7', 'Mở rộng ≤24', 'Cân bằng', 'Median', 'Gán nền toàn vùng', 'Giữ Q/mã KM'], formula: 'Bₜ = Median(Rᵣ), ∀t ∈ vùng KM r', variables: [{ symbol: 'r', meaning: 'Một vùng hoặc cụm CTKM liên tục' }, { symbol: 'Rᵣ', meaning: 'Tập ngày sạch quanh vùng r' }, { symbol: 't', meaning: 'Ngày thuộc vùng CTKM r' }] },
  { number: 5, phase: 1, title: 'Lấp nền & tổng hợp chu kỳ', shortTitle: 'Khóa chu kỳ', goal: 'Chỉ cộng sức mua cơ bản ngày vào chu kỳ đủ căn cứ.', flow: ['Chọn chu kỳ', 'Đếm ngày đủ nền', 'Chặn chu kỳ trống', 'Tìm ngày thiếu', 'Lấp bằng ngày sạch', 'Kiểm tra đủ 15 ngày', 'Ghi thành phần', 'Tổng hợp/khóa'], formula: 'Yⱼ = Σ Bₜ; lockedⱼ ⇔ unresolvedⱼ = 0', variables: [{ symbol: 'j', meaning: 'Chỉ số chu kỳ lịch' }, { symbol: 'Bₜ', meaning: 'Sức mua cơ bản cấp ngày, cột duy nhất được cộng' }, { symbol: 'Yⱼ', meaning: 'Sức mua cơ bản của chu kỳ j' }] },
  { number: 6, phase: 2, title: 'ABC theo giá trị tiêu thụ', shortTitle: 'ABC', goal: 'Xếp hạng giá trị tiêu thụ năm hóa từ chu kỳ đã khóa.', flow: ['Đếm N và tổng sức mua', 'Chuẩn hóa về 24 CK nếu N=6–23', 'Tính giá trị tiêu thụ', 'Sắp xếp giảm dần', 'Tính tỷ trọng/lũy kế', 'Chọn A rồi C', 'Gán B và kiểm tra'], formula: 'Q_năm = ΣY × a_N; V_năm = Q_năm × P', variables: [{ symbol: 'a_N', meaning: 'Hệ số chuẩn hóa năm: 1 khi N ≥ 24; 24/N khi 6 ≤ N < 24' }, { symbol: 'P', meaning: 'Đơn giá chuẩn, không dùng giá khuyến mãi' }, { symbol: 'N', meaning: 'Số chu kỳ khóa trong cửa sổ, tối đa 24' }, { symbol: 'Y', meaning: 'Sức mua cơ bản chu kỳ từ Chặng 5' }] },
  { number: 7, phase: 2, title: 'XYZ/D theo độ đều & độ thưa', shortTitle: 'XYZ/D', goal: 'Đo độ thưa và biến động của chuỗi nhu cầu.', flow: ['Chuỗi xᵢ', 'Đếm m', 'ADI', 'Nhánh Z', 'Lọc x>0', 'Tính μ', 'Tính σ', 'CV²', 'Khóa nhóm'], formula: 'ADI=n/m; CV²=(σ/μ)²; σ=√[Σ(x−μ)²/m]', variables: [{ symbol: 'n', meaning: 'Tổng số chu kỳ đã khóa' }, { symbol: 'm', meaning: 'Số chu kỳ có nhu cầu > 0; không phải độ dài mùa vụ' }, { symbol: 'x⁺', meaning: 'Các giá trị chu kỳ dương sau khi lọc chu kỳ bằng 0' }, { symbol: 'μ', meaning: 'Mức bán bình quân khi có nhu cầu' }, { symbol: 'σ', meaning: 'Độ lệch chuẩn quần thể trên m chu kỳ dương' }] },
  { number: 8, phase: 2, title: 'Ma trận chính sách ABC × XYZ', shortTitle: 'Chính sách', goal: 'Khóa mức phục vụ và ưu tiên vốn nhất quán.', flow: ['Lấy ABC', 'Lấy XYZ/D', 'Ghép 9 ô', 'Tách nhóm D', 'Gán SL/ưu tiên', 'Xét vai trò danh mục', 'Ghi chính sách', 'Bàn giao'], formula: 'Policy = Matrix(ABC, XYZ); D ∉ Matrix', variables: [{ symbol: 'ABC', meaning: 'Nhóm giá trị từ Chặng 6' }, { symbol: 'XYZ/D', meaning: 'Nhóm hành vi nhu cầu từ Chặng 7' }] },
  { number: 9, phase: 3, title: 'Kiểm tra mùa vụ nhóm Y', shortTitle: 'Mùa vụ', goal: 'Chỉ xác nhận mùa vụ khi tín hiệu lặp đủ vòng.', flow: ['Kiểm tra nhóm Y', 'Lấy chuỗi khóa', 'Gắn vòng/vị trí', 'Đối chiếu cùng vị trí', 'Tính Sₚ', 'Tính tỷ lệ lặp', 'Kết luận vị trí', 'Kết luận SKU'], formula: 'Rᵣ,ₚ = Yᵣ,ₚ / Ȳᵣ; Sₚ = mean(Rᵣ,ₚ)', variables: [{ symbol: 'r', meaning: 'Vòng mùa vụ' }, { symbol: 'p', meaning: 'Vị trí 1…24 trong vòng' }, { symbol: 'Yᵣ,ₚ', meaning: 'Sức mua tại vị trí p của vòng r' }] },
  { number: 10, phase: 3, title: 'Kiểm tra xu hướng nhóm Y', shortTitle: 'Xu hướng', goal: 'Đo xu hướng bền vững trên 12 chu kỳ cuối.', flow: ['Đọc Y/mùa vụ', 'Kiểm tra đủ 12 CK', 'Lấy 12 CK cuối', 'Chia 3×4', 'Tính g₁/g₂', 'So ngưỡng ±5%', 'Giới hạn 15%', 'Bàn giao công tắc'], formula: 'g₁=(Ȳ₂−Ȳ₁)/Ȳ₁; g₂=(Ȳ₃−Ȳ₂)/Ȳ₂', variables: [{ symbol: 'Ȳ₁…Ȳ₃', meaning: 'Trung bình ba đoạn liên tiếp, mỗi đoạn 4 chu kỳ' }, { symbol: 'g₁/g₂', meaning: 'Tốc độ thay đổi giữa hai cặp đoạn' }] },
  { number: 11, phase: 3, title: 'Chọn & chạy mô hình dự báo nền', shortTitle: 'Dự báo nền', goal: 'Chọn mô hình từ đầu ra đã khóa, không tự phân loại lại.', flow: ['Chọn nhánh', 'Chia TRAIN/TEST', 'Tối ưu trên TRAIN', 'Dự báo TEST', 'Tính sai số', 'So ngưỡng đúng ô', 'Mô phỏng tác động', 'Quyết định khóa', 'Bàn giao nền'], formula: 'RMSE; nRMSE; WAPE=Σ|Aₜ−Fₜ|/ΣAₜ; Bias=Σ(Fₜ−Aₜ)/ΣAₜ', variables: [{ symbol: 't', meaning: 'Chỉ số chu kỳ theo thời gian; tuyệt đối không trộn ngẫu nhiên' }, { symbol: 'Aₜ/Fₜ', meaning: 'Thực tế / dự báo ở chu kỳ t' }, { symbol: 'k', meaning: 'Số bước dự báo tương lai trong Fₜ₊ₖ' }] },
  { number: 12, phase: 3, title: 'Hệ số KM từ lịch sử', shortTitle: 'Hệ số KM', goal: 'Học mức tăng bán từ các vùng CTKM đủ căn cứ.', flow: ['Nhóm vùng theo loại', 'Kiểm tra nền/Q', 'Loại stockout', 'Tính từng K', 'Gom K cùng nhóm', 'Kiểm tra số mẫu', 'Median/giới hạn'], formula: 'Kᵣ = Qᵣ / Nᵣ; K = Median(Kᵣ)', variables: [{ symbol: 'Qᵣ', meaning: 'Tổng bán ghi nhận trong vùng CTKM r' }, { symbol: 'Nᵣ', meaning: 'Tổng nền tự nhiên của vùng r' }, { symbol: 'K', meaning: 'Hệ số tăng bán CTKM; khác hoàn toàn k cân bằng ở Chặng 3' }] },
  { number: 13, phase: 3, title: 'Áp CTKM tương lai', shortTitle: 'Dự báo cuối', goal: 'Chỉ nhân hệ số KM vào phần nền thuộc ngày KM.', flow: ['Đọc dự báo nền', 'Kiểm tra kế hoạch xác nhận', 'Kiểm tra K', 'Ghép nhóm KM', 'Tách phần nền', 'Chốt dự báo cuối'], formula: 'F = Fᵦ×(1−n/M) + Fᵦ×(n/M)×K', variables: [{ symbol: 'Fᵦ', meaning: 'Dự báo nền chưa áp CTKM' }, { symbol: 'n', meaning: 'Số ngày KM trong chu kỳ' }, { symbol: 'M', meaning: 'Số ngày của chu kỳ kế hoạch' }, { symbol: 'K', meaning: 'Hệ số CTKM đã khóa hoặc duyệt' }] },
  { number: 14, phase: 4, title: 'Lịch nguồn hàng & vị thế tồn', shortTitle: 'Nguồn hàng', goal: 'Tính hàng tự do tại từng mốc nguồn hàng.', flow: ['Chọn SKU/NCC', 'Sắp xếp mốc', 'Cộng inbound xác nhận', 'Trừ cam kết', 'Tính I_free từng mốc'], formula: 'I_free(t)=OnHand+ΣInbound≤t−ΣCommitted≤t', variables: [{ symbol: 't', meaning: 'Mốc thời gian nguồn hàng cần đánh giá' }, { symbol: 'Inbound', meaning: 'Chỉ lô có ngày về kho đã xác nhận' }, { symbol: 'Committed', meaning: 'Nhu cầu đã cam kết trước mốc t' }] },
  { number: 15, phase: 5, title: 'Tồn kho an toàn', shortTitle: 'Safety stock', goal: 'Bảo vệ đồng thời biến động nhu cầu và lead time.', flow: ['Đọc 5 nhóm đầu vào', 'Quy đổi LT', 'Tính D̄', 'Tính σd', 'Chọn Z', 'Kiểm tra đủ dữ liệu', 'Tính SS', 'Gắn cảnh báo/khóa'], formula: 'SS=Z×√(LT̄×σd² + D̄²×σLT²)', variables: [{ symbol: 'Z', meaning: 'Hệ số chuẩn theo mức phục vụ Chặng 8' }, { symbol: 'LT̄', meaning: 'Lead time trung bình đã quy đổi về chu kỳ' }, { symbol: 'σLT', meaning: 'Độ lệch chuẩn lead time cùng đơn vị chu kỳ' }, { symbol: 'D̄', meaning: 'Dự báo cuối trung bình trong vùng bảo vệ' }, { symbol: 'σd', meaning: 'Độ lệch chuẩn mẫu của sai số backtest' }] },
  { number: 16, phase: 5, title: 'Số đặt trước ngân sách & MOQ', shortTitle: 'Số đặt/MOQ', goal: 'Tính phần thiếu trong vùng bao phủ rồi làm tròn đúng quy cách mua.', flow: ['Đọc dự báo cuối', 'Đọc vị thế tồn', 'Đọc tồn an toàn', 'Đọc MOQ/quy cách', 'Xác định vùng bao phủ', 'Tính nhu cầu bao phủ', 'Tính hàng tự do', 'Tính số cần', 'Kiểm tra số cần > 0', 'Làm tròn MOQ', 'Tính phần dư', 'Khóa đầu ra'], formula: 'Qraw=max(0,Dcover+SS−Ifree); Qorder=⌈Qraw/MOQ⌉×MOQ', variables: [{ symbol: 'Dcover', meaning: 'Tổng dự báo cuối trong vùng cần bảo vệ' }, { symbol: 'SS', meaning: 'Tồn kho an toàn từ Chặng 15' }, { symbol: 'Ifree', meaning: 'Hàng tự do dự kiến từ Chặng 14' }, { symbol: 'MOQ', meaning: 'Số lượng đặt tối thiểu hoặc bước làm tròn' }] },
  { number: 17, phase: 6, title: 'Phân bổ ngân sách', shortTitle: 'Ngân sách', goal: 'Cấp vốn theo ưu tiên đã khóa mà không sửa dự báo hay số đặt.', flow: ['Đọc số đặt sau MOQ', 'Đọc giá mua', 'Đọc ngân sách', 'Đọc ưu tiên C8', 'Tính tổng giá trị', 'Kiểm tra đủ vốn', 'Xếp ưu tiên', 'Cấp theo thứ tự', 'Ghi cắt/hoãn', 'Khóa đầu ra'], formula: 'Value=Qorder×PurchasePrice; cấp theo ưu tiên đến khi hết ngân sách', variables: [{ symbol: 'P', meaning: 'Điểm/thứ tự ưu tiên chính sách' }, { symbol: 'B', meaning: 'Ngân sách kỳ' }] },
  { number: 18, phase: 6, title: 'Duyệt ngoại lệ & phát hành', shortTitle: 'Phát hành', goal: 'Chỉ phát hành dòng đủ vốn, đủ thông tin và không có ngoại lệ cần duyệt.', flow: ['Đọc số được cấp vốn', 'Đọc điều kiện mua', 'Đọc ngoại lệ C8–16', 'Chọn SKU–NCC', 'Kiểm tra số vốn > 0', 'Kiểm tra đủ thông tin', 'Kiểm tra ngoại lệ', 'Chờ bổ sung/duyệt hoặc phát hành', 'Khóa đầu ra'], formula: 'Release = Funded ∧ Complete ∧ ¬Exception', variables: [{ symbol: 'Funded', meaning: 'Số lượng đã được cấp vốn ở Chặng 17' }, { symbol: 'Complete', meaning: 'Đủ ETA, MOQ, giá mua, NCC và điều kiện đơn mua' }] },
  { number: 19, phase: 6, title: 'Hậu kiểm & đề xuất kỳ sau', shortTitle: 'Hậu kiểm', goal: 'Đo kết quả, tách nguyên nhân và chỉ tạo đề xuất cho phiên tương lai.', flow: ['Đọc dự báo/số phát hành', 'Đọc thực tế vận hành', 'Đọc ngân sách/duyệt', 'Đo sai số dự báo', 'Đo thiếu/dư tồn', 'Đo trễ nguồn hàng', 'Đo tác động ngân sách/duyệt', 'Tách nguyên nhân', 'Kiểm tra cần thay đổi', 'Tạo đề xuất hoặc theo dõi', 'Khóa báo cáo'], formula: 'WAPE=Σ|A−F|/ΣA', variables: [{ symbol: 'A', meaning: 'Nhu cầu thực tế sau kỳ' }, { symbol: 'F', meaning: 'Dự báo cuối đã phát hành' }] },
] as const;

export const SERVICE_LEVELS: Record<string, number> = {
  AX: 97, AY: 95, AZ: 92, BX: 95, BY: 92, BZ: 88, CX: 90, CY: 85, CZ: 80,
};

export const CAPITAL_PRIORITIES: Record<string, string> = {
  AX: 'Rất cao', AY: 'Rất cao', AZ: 'Cao',
  BX: 'Cao', BY: 'Trung bình', BZ: 'Trung bình thấp',
  CX: 'Trung bình thấp', CY: 'Thấp', CZ: 'Rất thấp',
};

export const Z_VALUES: Record<number, number> = {
  80: 0.84, 85: 1.04, 88: 1.17, 90: 1.28, 92: 1.41, 95: 1.65, 97: 1.88, 97.5: 1.96, 99: 2.33,
};
