/**
 * THỬ NGHIỆM (2026-07-16, yêu cầu người vận hành): danh sách tên CTKM dạng COMBO trích từ
 * real.dataset.json (token promoCode chứa "Combo", 151 tên). Nạp vào STANDING_PROMOTION_CODES
 * để Chặng 1 gỡ các mã này khỏi promoCode — ngày CHỈ dính combo được xử lý như ngày bán bình thường
 * (không chuẩn hóa CTKM ở Chặng 4). CHƯA phải chính sách đã phê duyệt; muốn tắt thử nghiệm:
 * đặt lại STANDING_PROMOTION_CODES = [] trong policy.ts.
 */
export const COMBO_PROMOTION_CODES: readonly string[] = [
  "Best Price - Combo 2 chai dầu gạo Tsuno 1500g",
  "Black Friday- Combo mua 2 tặng 1 dầu gạo Tsuno",
  "Combo 1 chai Dầu gạo Nhật Bản Tsuno 1.5kg tặng 1 gói Rong biển Wakame",
  "Combo 1 chai Nước tương Chibi Nhật Bản cho bé 150ml tặng 1 gói Bánh viên Boro rau củ cho bé 45g",
  "Combo 1 hũ Nước hầm xương cô đặc cao cấp Kouki 1kg tặng 1 chai Súp nấu lẩu cô đặc Miso cay Daisho 1.18kg",
  "Combo 1 tặng 1 Chất tẩy rửa lồng máy giặt Rocket 390ml",
  "Combo 1 thùng 24 lon Nước ngọt Coca cola Nhật Bản 300ml",
  "Combo 1 thùng 24 lon Nước ngọt Coca Cola Nhật Bản 300ml",
  "Combo 2  Nước rửa chén Wai Rookie V nhà bếp 4L",
  "Combo 2 bịch Bột làm sạch lồng máy giặt Rocket 120g",
  "Combo 2 bịch Chất tẩy rửa lồng máy giặt Rocket 390ml",
  "Combo 2 bịch Rong biển cắt Wakame 40g",
  "Combo 2 Bột tẩy lồng máy giặt kháng khuẩn, chống nấm mốc Rocket 120g",
  "Combo 2 chai dầu gạo Best Price tặng bột nêm dashi tảo bẹ kombu 140g",
  "Combo 2 chai dầu gạo Nhật Bản Tsuno nguyên chất 1500g",
  "Combo 2 chai Dầu gạo Nhật Bản Tsuno nguyên chất 1500g",
  "Combo 2 chai dầu gạo Tsuno 1,5kg tặng 1 chai cùng loại",
  "Combo 2 chai Dầu gạo Tsuno nguyên chất 1500g - Giảm 19% tặng Giấy thấm dầu thực phẩm 40 tờ 27x25cm",
  "Combo 2 chai nước rửa chén 600ml tặng 1 bịch rửa chén",
  "Combo 2 chai nước rửa chén hương chanh Rocket 600ml",
  "Combo 2 Chất tẩy rửa lồng máy giặt Rocket 390ml",
  "Combo 2 đôi Bao tay chống trượt hở ngón Free size (Nhiều mẫu)",
  "Combo 2 gói Bột làm sạch lồng máy giặt Rocket 120g",
  "Combo 2 gói Rong biển cắt Wakame 100g",
  "Combo 2 gói Rong biển cắt Wakame 40g",
  "Combo 2 gói Rong biển Wakame 40g và súp Miso sò lụa ăn liền Hikari Miso 128g (8 gói)",
  "Combo 2 Hộp đựng thực phẩm Nhật Bản trữ đông, trữ mát, dùng lò vi sóng Nakaya 2L và 3L",
  "Combo 2 Mì Ramen ăn liền Mama",
  "Combo 2 Mì Soba Nhật Bản 200g",
  "Combo 2 Rong biển cắt Wakame 100g",
  "Combo 2 Rong biển cắt Wakame 40g",
  "Combo 2 Rong biển cắt Wakame 40g tặng 1 bịch cùng loại",
  "Combo 2 túi Bột làm sạch lồng máy giặt Rocket 120g",
  "Combo 2 túi Chất tẩy rửa lồng máy giặt Rocket 390ml",
  "Combo 3  Nước rửa chén Wai Rookie V nhà bếp 4L",
  "Combo 3 hộp nhựa đựng thực phẩm Nhật Bản trữ đông, trữ mát, dùng lò vi sóng Nakaya 3L, 2L, 1.3L",
  "Combo 4 hộp nhựa đựng thực phẩm Nakaya",
  "Combo 5 gói Mì Soba Nhật Bản 200g",
  "Combo 6 hộp Cháo thịt Asuzac 36g & 6 hộp Cháo nấm Asuzac 36g",
  "Combo 6 Hộp nhựa đựng thực phẩm Nakaya (2 hộp 1.3L, 2 hộp 2L, 2 hộp 3L)",
  "Combo Dầu gạo Nhật Bản Tsuno 1500g và Bột ngọt Ajinomoto 1kg",
  "Combo Dầu gạo Nhật Bản Tsuno 1500g và Đường vàng Nhật Bản 1kg",
  "Combo dầu gạo Tsuno nguyên chất 1.5kg (1636ml) và Hạt nêm chiết xuất thị và rau Youki 520g",
  "Combo Dầu gạo Tsuno nguyên chất 1.5kg (1636ml) và Nước hầm xương cô đặc cao cấp Kouki 1kg",
  "Combo Mì Mug Ramen Nissin 94g (4 gói) tặng Thực phẩm bổ sung: Bánh sữa đậu nành Chobo cho bé 65g",
  "Combo mì Soba 200g và Súp ăn mì Yamagen 1L",
  "Combo Mirin Hinode 400ml và Nước tương Tsuyu ăn mì Yamagen 300ml",
  "Combo mua 1 chai Nước tương Chibi cho bé 150ml tặng 1 bịch Khẩu trang trẻ em 8 cái",
  "Combo mua 1 chai Nước tương Chibi Nhật Bản cho bé 150ml tặng 1 Chốt an toàn cho bé",
  "Combo mua 1 chai Nước tương Chibi Nhật Bản cho bé 150ml tặng 1 Dĩa phần 4 ngăn (Logo Chibi)",
  "Combo mua 1 mì Mug Ramen Nissin tặng 1 gói Bột nêm Dashi tảo bẹ Kombu (6gx7 gói)",
  "Combo mua 1 Nước giặt kháng khuẩn khử mùi Deostyle 1,65kg tặng nước xả và chất tẩy lồng giặt",
  "Combo mua 1 tặng 1 Mì Soba Nhật Bản 200g",
  "Combo mua 1 tặng 1 Rong biển cắt Wakame 100g",
  "Combo mua 2 Bột nêm Dashi tảo bẹ Kombu Shimaya tặng 1 bịch cùng loại",
  "Combo mua 2 chai Dầu gạo Nhật Bản Tsuno nguyên chất 1500g (1636ml) tặng 1 gói Mì Somen rau củ Nhật Bản 320g",
  "Combo mua 2 chai Dầu gạo Nhật Bản Tsuno nguyên chất 1500g tặng 1 gói Mì Ramen ăn liền Mama 360g (12 góix30g)",
  "Combo Mua 2 chai Nước rửa chén trung tính hương chanh Rocket 600g tặng 1 túi refill 500g",
  "Combo mua 2 Dầu gạo Nhật Bản Tsuno 1.5kg chỉ 438K tặng thêm Rong biển hải sản nấu canh, súp Miso Sanko 85g",
  "Combo MUA 2 Dầu gạo Nhật Bản Tsuno nguyên chất 1500g (1636ml) TẶNG Bột nêm Dashi tảo bẹ Kombu Shimaya 140g",
  "Combo mua 2 Dầu gạo Nhật Bản Tsuno nguyên chất 1500g (1636ml) tặng Màng bọc thực phẩm Nhật Bản Asahi Wrap 22cmx15m",
  "Combo mua 2 Dầu gạo Nhật Bản Tsuno nguyên chất 1500g tặng 1 chai cùng loại",
  "Combo Mua 2 dầu gạo Tsuno nguyên chất 1500g (1636ml) tặng Chảo chống dính Pearl 13x18cm",
  "Combo mua 2 gói Rong biển cắt Wakame 40g tặng 1 hộp Miso Dashi trộn sẵn Marukome (Cắt giảm 20% muối) 375g",
  "Combo mua 2 gói Rong biển Wakame 40g tặng 1 Miso Dashi trộn sẵn Marukome 375g",
  "Combo mua 2 Mì Soba Nhật Bản 200g tặng 1 bịch cùng loại",
  "Combo mua 2 nước rửa chén hương chanh tặng 1 hương táo xanh",
  "Combo mua 2 Nước rửa chén hương chanh tặng 1 nước rửa chén hương cam",
  "Combo mua 2 Nước rửa chén Rocket hương chanh tặng 1 chai cùng loại",
  "Combo mua 2 Nước rửa chén trung tính hương chanh Rocket 600g tặng 1 túi refill 500g cùng loại",
  "Combo mua 2 Rong biển cắt Wakame 40g tặng 1 bịch cùng loại",
  "Combo mua 2 tặng 1  Dầu gạo Nhật Bản Tsuno nguyên chất 1500g (1636ml)",
  "Combo mua 2 tặng 1 Bột làm sạch lồng máy giặt Rocket 120g",
  "Combo mua 2 tặng 1 Bột trà xanh Matcha Uji Yanoen 30g",
  "Combo mua 2 tặng 1 Cháo nấm Asuzac 36g",
  "Combo mua 2 tặng 1 Chất tẩy rửa lồng máy giặt Rocket 390ml",
  "Combo mua 2 tặng 1 dầu gạo Nhật Bản Tsuno nguyên chất 1.5kg (1636ml)",
  "Combo mua 2 tặng 1 Dầu gạo Nhật Bản Tsuno nguyên chất 1500g",
  "Combo mua 2 tặng 1 Dầu gạo Nhật Bản Tsuno nguyên chất 1500g (1636ml)",
  "Combo mua 2 tặng 1 Hạt dẻ Organic 216g (108g x 2 gói)",
  "Combo mua 2 tặng 1 Hộp đựng thực phẩm Nhật Bản trữ đông, trữ mát, dùng lò vi sóng Nakaya 3L",
  "Combo mua 2 tặng 1 Mì Soba Nhật Bản 200g",
  "Combo mua 2 tặng 1 Nước rửa chén Rocket 600g",
  "Combo mua 2 tặng 1 Rong biển cắt Wakame 40g",
  "Combo MUA 2 TẶNG 1 Rong biển cắt Wakame 40g",
  "Combo Mua 3 chai nước rửa chén Rocket 600g tặng 2 túi nước rửa chén refill 500g",
  "Combo mua 3 tặng 2 Nước rửa chén trung tính Rocket 600ml",
  "Combo mua chai tặng túi Nước rửa chén trung tính hương chanh Rocket",
  "Combo mua chai và túi Nước rửa chén trung tính hương chanh Rocket tặng Bao tay cao su size L màu xanh",
  "Combo mua Dầu gạo Nhật Bản Tsuno nguyên chất 1500g giá 235k tặng 1 gói Mì Ramen ăn liền Mama 360g (12 góix30g)",
  "Combo mua gói 100g tặng gói 40g Rong biển cắt Wakame",
  "Combo mua Hạt dẻ Organic 216g giá 119k tặng Nho khô phủ đậu nành Kinako Tokai 85g",
  "Combo mua Hạt nêm Dashi tảo bẹ Kombu Maruhachi 500g tặng Rong biển cắt Wakame 40g",
  "Combo mua Mì không chiên vị nước tương (5 gói) tặng rong biển wakame 40g",
  "Combo mua Mì không chiên vị xương hầm (5 gói) tặng rong biển wakame 40g",
  "Combo mua Mì xào Yakisoba (5 gói) tặng rong biển wakame 40g",
  "Combo Mua Nước lau sàn Kenko Clean 2L tặng Nước rửa chén trung tính hương chanh Rocket 600g",
  "Combo mua Nước tương Chibi  tặng  Dầu gạo Tsuno 180g",
  "Combo mua nước tương Chibi 150ml tặng Bánh sữa đậu nành 70g",
  "Combo mua Nước tương Chibi 150ml tặng Bánh viên Boro khoai lang tím",
  "Combo mua Nước tương Chibi cho bé 150ml tặng 1 Bánh viên Boro rau củ 45g",
  "Combo mua Nước tương Chibi Nhật Bản cho bé 150ml giá 85k tặng Bánh sữa viên Boro bổ sung lợi khuẩn 75g",
  "Combo mua Nước tương Chibi Nhật Bản cho bé 150ml tặng  Mì ăn dặm không muối Ishimaru 100g",
  "Combo mua Nước tương Chibi Nhật Bản cho bé 150ml tặng Bánh sữa viên Boro 70g  (HSD: 7/2024)",
  "Combo mua Nước tương Chibi Nhật Bản cho bé 150ml tặng Bánh viên Boro khoai lang tím cho bé 45g",
  "Combo mua Nước tương Chibi Nhật Bản cho bé 150ml tặng Mì ăn dặm không muối Ishimaru 100g",
  "Combo mua Nước tương Chibi Nhật Bản cho bé 150ml tặng Nắp bọc ổ điện an toàn 8 cái",
  "Combo mua nước tương Chibi tặng bánh sữa viên",
  "Combo mua Rong biển cắt Wakame 100g tặng 2 gói  Súp Miso rong biển Wakame ăn liền Hikari Miso 216g (12 gói)",
  "Combo mua Rong biển cắt Wakame 100g tặng gói cùng loại 40g",
  "Combo mua Rong biển cắt Wakame 100g tặng Miso Dashi trộn sẵn Marukome (Cắt giảm 20% muối) 375g",
  "Combo mua Rong biển hỗn hợp Wakame Hijiki 65g tặng Rong biển cắt Wakame 100g",
  "Combo mua Rổ quay rau tặng dầu gạo Nhật Bản Tsuno nguyên chất 1500g",
  "Combo mua Viên giặt xả khử mùi chống nhăn 4D Gel Ball Bold P&G hương hoa 31 viên tặng bột tẩy lồng máy giặt",
  "Combo Nước hầm xương cô đặc cao cấp Kouki 1kg và Dầu gạo Nhật Bản Tsuno nguyên chất 1500g (1636ml)",
  "Combo Nước tương Chibi cho bé 150ml tặng 1 chai Dầu gạo Tsuno  180g",
  "Combo siêu hời mua 1 chai Dầu gạo Nhật Bản Tsuno nguyên chất 1500g (1636ml) giá 229,000đ tặng Giấy thấm dầu nấu ăn 45 tờ 22x20.8cm",
  "Combo siêu hời mua 1 tặng 1 Mì Soba Nhật Bản 200g",
  "Combo siêu hời mua 2 chai Nước rửa chén trung tính hương chanh Rocket 600g tặng túi refill 500g cùng loại",
  "Combo siêu hời mua 2 gói Bột nêm Dashi tảo bẹ Kombu Shimaya 42g (6gx7gói) tặng 1 gói Bột nêm Dashi tảo bẹ Kombu Shimaya 140g",
  "Combo siêu hời mua 2 hộp Viên giặt xả 4 trong 1 P&G hương hoa 28 viên tặng 1 hộp 11 viên và 1 Bột tẩy lồng giặt 120g",
  "Combo siêu hời mua 2 hộp Viên giặt xả 4 trong 1 P&G hương nắng mai 28 viên tặng 1 hộp 11 viên và 1 Bột tẩy lồng giặt 120g",
  "Combo siêu hời mua 2 Nước rửa chén Wai Rookie V nhà bếp 4L tặng bình 2L (có vòi nhấn)",
  "Combo siêu hời mua 2 tặng 1 Mì Soba Nhật Bản 200g",
  "Combo siêu hời mua 2 tặng 1 Rong biển cắt Wakame 40g",
  "Combo siêu hời mua 2 túi Viên giặt xả 4 in 1 P&G hương hoa trà trắng 28 viên tặng 1 hộp 11 viên và 1 Bột tẩy lồng giặt 120g",
  "Combo siêu hời mua 2 túi Viên giặt xả 4 trong 1 P&G hương nắng mai 28 viên tặng 1 hộp 11 viên và 1 Bột tẩy lồng giặt 120g",
  "Combo siêu hời mua Chảo chống dính cao cấp Nhật Bản Hokuriku 20cm Plateado tặng Dầu gạo Nhật Bản Tsuno nguyên chất 1500g (1636ml)",
  "Combo siêu hời mua Chảo chống dính cao cấp Nhật Bản Hokuriku 26cm Plateado tặng Dầu gạo Nhật Bản Tsuno nguyên chất 1500g (1636ml)",
  "Combo siêu hời mua Dầu gạo Nhật Bản nguyên chất Tsuno 1500g (1636ml) tặng Bột nêm Dashi tảo bẹ Kombu Shimaya (6gx7gói)",
  "Combo siêu hời mua Nước hầm xương cô đặc cao cấp Kouki 1kg tặng Mì udon và mì somen Nhật Bản 200g",
  "Combo siêu hời mua Rong biển cắt Wakame 100g tặng Bột nêm Dashi tảo bẹ Kombu Shimaya 42g (6gx7gói)",
  "Combo siêu tiết kiệm 1 chai Dầu gạo Nhật Bản Tsuno nguyên chất 1500g (1636ml) và 2 hộp 500g (545ml)",
  "Combo siêu tiết kiệm 1 Dầu gạo Nhật Bản Tsuno nguyên chất 1500g (1636ml) và 1 Dầu gạo Nhật Bản Tsuno nguyên chất 500g (545ml)",
  "Combo siêu tiết kiệm 1 thùng 12 hôp Cháo nấm Asuzac 36g",
  "Combo siêu tiết kiệm 1 thùng 24 lon Nước ngọt có ga vị truyền thống Coca Cola Original Taste 300ml",
  "Combo siêu tiết kiệm 1 thùng 3 can Nước rửa chén Wai Rookie V nhà bếp 4L",
  "Combo siêu tiết kiệm 2 Bột tẩy lồng máy giặt kháng khuẩn, chống nấm mốc Rocket 120g",
  "Combo siêu tiết kiệm 2 chai Dầu gạo Nhật Bản nguyên chất Tsuno 1500g (1636ml)",
  "Combo siêu tiết kiệm 2 chai Dầu gạo Nhật Bản Tsuno nguyên chất 1500g (1636ml)",
  "Combo siêu tiết kiệm 2 chai Dầu gạo Nhật Bản Tsuno nguyên chất 1500g (1636ml) tặng Giấy thấm dầu nấu ăn 45 tờ 22x20.8cm",
  "Combo siêu tiết kiệm 2 Dầu gạo Nhật Bản Tsuno nguyên chất 1500g (1636ml) và 3 Dầu gạo Nhật Bản Tsuno nguyên chất 500g (545ml)",
  "Combo siêu tiết kiệm 3 chai Dầu gạo Nhật Bản Tsuno nguyên chất 1500g (1636ml)",
  "Combo siêu tiết kiệm 3 Chất tẩy rửa lồng máy giặt Rocket 390ml",
  "Combo siêu tiết kiệm 3 Hộp đựng thực phẩm Nhật Bản trữ đông, trữ mát, dùng lò vi sóng Nakaya 1.3L,2L,3L",
  "Combo siêu tiết kiệm 3 Hộp đựng thực phẩm Nhật Bản trữ đông, trữ mát, dùng lò vi sóng Nakaya 3 size (1.3L, 2L, 3l)",
  "Combo siêu tiết kiệm 3 Nước rửa chén chuyên dùng Wai GreenMild 4L",
  "Combo siêu tiết kiệm 3 túi Bột tẩy lồng máy giặt kháng khuẩn, chống nấm mốc Rocket 120g",
  "Combo siêu tiết kiệm 3 túi Chất tẩy rửa lồng máy giặt Rocket 390ml",
  "Combo siêu tiết kiệm Pudding xoài và thạch trái cây (10 cái) - HSD: 1/3/26 và Hạt dẻ Organic (108g x 2 gói)",
  "Combo siêu tiết kiệm Rong biển hỗn hợp Wakame Hijiki 60g và Rong biển cắt Wakame 100g",
];
